### ISSUE TITLE
Remove perl version?

### ISSUE THREAD

**Issue by superMDguy** [amahabal/PySeqsee#23]
Do you want to keep the perl version as part of the project?  Or could I delete it or move it to a separate branch?

**Comment by amahabal** [comment]
Go for it. I was thinking of doing that anyway, and the code is available
in the seqsee repository in any case. I am going to add you as a
collaborator on the project, so (if I understand things right), you should
be able to submit this change directly.

Thanks,
  Abhijit

**Comment by superMDguy** [comment]
I just did it in commit d247aeb.
