### ISSUE TITLE
Make updating docs easier

### ISSUE THREAD

**Issue by superMDguy** [amahabal/PySeqsee#25]
@amahabal could you modify the github pages settings so the root directory for the website is `docs/_build/html`?  That way the docs would auto update by just doing `make html`, without switching over to the gh-pages branch and modifying it.

**Comment by amahabal** [comment]
I agree that the current setting is cumbersome.

Do you know what I would need to do? I see the following options on the
settings page for the source of github pages

(A) the gh-pages branch (which is what I have currently).
(B) master branch
(C) master branch /docs folder.

Does (C) correspond to what you are suggesting?

Thanks,
  Abhijit

**Comment by superMDguy** [comment]
C would be the best option, though it's not ideal.  We'd have to rename the current `docs` folder to something else, and use the new `docs` folder exclusively for the compiled html

**Comment by amahabal** [comment]
Alright, I will make that transition tonight (unless you beat me to it!)

**Comment by superMDguy** [comment]
I actually just found [this gist](https://gist.github.com/cobyism/4730490), which gives a simpler way to transfer a folder to the gh-pages branch.  Now, to update the docs we can just do

```bash
$ make html
$ git subtree push --prefix docs/_build/html origin gh-pages
```

That's simpler than having to checkout the `gh-pages` branch, which is what I was doing.

**Comment by amahabal** [comment]
I use the following workflow that I am not too unhappy about. It does not involve switching branches. See if that works for you.

I have two repositories checked out for Pyseqsee. One tracks the master branch, the other the gh-pages branch. When I am ready to push documentation, I do "make html" in the master branch, go to the other repository, and copy files from there, and push. 

Ugly, but workable with a script. This avoids making two copies of the documentation (I think currently the _build directory on master is gitignored). Would this hack work for you?

**Comment by superMDguy** [comment]
Yeah, I don't think there's any simpler solution by changing the github pages setings.
